# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5112b9d75c74a8bdd8c230a0fc3db7f6dc8cda67d475f6092ef90e3b2029d3cc510aba008c6cad324392980198479700e5be8a107b16bec810dd3d1ea7525db7

test:
  secret_key_base: c27cbe0c2e1f8d720783190193e2dc48cb1c7fd63691687d8a6af386fb58015475e8a83f4cf7f4e654c876502fcccf6b2006f4e93daaf5acc28f228cde1e162c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
